# Generated by Django 2.2.2 on 2019-07-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenpythonpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='answered_comp',
        ),
    ]
