# Generated by Django 2.2.3 on 2019-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('p_answer1', models.TextField()),
                ('p_answer2', models.TextField()),
                ('p_answer3', models.TextField()),
                ('p_answer4', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
